//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCinema
    {
        public GroupCinema()
        {
            this.Cinemas = new HashSet<Cinema>();
            this.PartnerAccounts = new HashSet<PartnerAccount>();
            this.TypeOfSeats = new HashSet<TypeOfSeat>();
        }
    
        public int GroupId { get; set; }
        public string logoImg { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Cinema> Cinemas { get; set; }
        public virtual ICollection<PartnerAccount> PartnerAccounts { get; set; }
        public virtual ICollection<TypeOfSeat> TypeOfSeats { get; set; }
    }
}
