//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietCineAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSchedule()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int scheduleId { get; set; }
        public int filmId { get; set; }
        public int timeId { get; set; }
        public int roomId { get; set; }
        public System.DateTime scheduleDate { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Room Room { get; set; }
        public virtual ShowTime ShowTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
