//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BookingTickets = new HashSet<BookingTicket>();
        }
    
        public int customerId { get; set; }
        public string userId { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<BookingTicket> BookingTickets { get; set; }
    }
}
