//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaBookingDBEntities : DbContext
    {
        public CinemaBookingDBEntities()
            : base("name=CinemaBookingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminAccount> AdminAccounts { get; set; }
        public DbSet<BookingTicket> BookingTickets { get; set; }
        public DbSet<Cinema> Cinemas { get; set; }
        public DbSet<CinemaManager> CinemaManagers { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DigitalType> DigitalTypes { get; set; }
        public DbSet<Film> Films { get; set; }
        public DbSet<GroupCinema> GroupCinemas { get; set; }
        public DbSet<MovieSchedule> MovieSchedules { get; set; }
        public DbSet<PartnerAccount> PartnerAccounts { get; set; }
        public DbSet<Promotion> Promotions { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Seat> Seats { get; set; }
        public DbSet<ShowTime> ShowTimes { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TypeOfSeat> TypeOfSeats { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
    }
}
